{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.user (omit .Values "global" "exports") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
data:
  STARHUB_SERVER_API_TOKEN: {{ include "server.api.token" . | quote }}
  STARHUB_DATABASE_TIMEZONE: {{ default "UTC" $conf.timezone | quote }}
  STARHUB_SERVER_GITSERVER_HOST: {{ include "gitea.internal.endpoint" . | quote }}
  STARHUB_JWT_SIGNING_KEY: "e2kk6awudc3620ed9a"
  OPENCSG_USER_SERVER_PORT: {{ include "user.internal.port" . | quote }}
  OPENCSG_USER_SERVER_SIGNIN_SUCCESS_REDIRECT_URL: {{ include "csghub.callback.user" . | quote }}
  STARHUB_SERVER_CASDOOR_CERTIFICATE: "/starhub-bin/casdoor/tls.crt"
