{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "server") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "server") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "server" }}
      targetPort: 8080
      protocol: TCP
      name: server
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "server") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "user") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "user") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "user" }}
      targetPort: 8080
      protocol: TCP
      name: user
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "user") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "accounting") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "accounting") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "accounting" }}
      targetPort: 8086
      protocol: TCP
      name: accounting
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "accounting") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "dataviewer") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "dataviewer") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "csghub.svc.port" "dataviewer" }}
      targetPort: 8093
      protocol: TCP
      name: dataviewer
  selector:
    {{- include "common.labels" (dict "context" . "service" "dataviewer") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "notification") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "notification") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "notification" }}
      targetPort: 8095
      protocol: TCP
      name: notification
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "notification") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "gateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "gateway") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: {{ include "rproxy.nginx.ip" . }}
  ports:
    - port: {{ include "csghub.svc.port" "rproxy" }}
      targetPort: 8083
      protocol: TCP
      name: rproxy
    - port: 80
      targetPort: 80
      protocol: TCP
      name: rproxy-nginx
    {{- if .Values.global.moderation.enabled }}
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: moderation
    {{- end }}
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: aigateway
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "gateway") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "portal") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "portal") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "portal" }}
      targetPort: 8090
      protocol: TCP
      name: portal
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "portal") | nindent 4 }}
---
{{- if .Values.global.deploy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "runner") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "runner" }}
      targetPort: 8082
      protocol: TCP
      name: runner
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "runner") | nindent 4 }}
{{- end }}
---
{{- if or (and .Values.csghub.portal.docs.host .Values.csghub.portal.docs.port) .Values.csghub.portal.docs.domain }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "docs") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
spec:
  {{- if .Values.csghub.portal.docs.domain }}
  type: ExternalName
  externalName: {{ .Values.csghub.portal.docs.domain | trimPrefix "https://" | trimPrefix "http://" }}
  {{- else }}
  type: ClusterIP
  ports:
    - port: {{ .Values.csghub.portal.docs.port }}
      targetPort: {{ .Values.csghub.portal.docs.port }}
      protocol: TCP
      name: docs
  {{- end }}
{{- end }}
---
{{- if and .Values.csghub.portal.docs.host .Values.csghub.portal.docs.port }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "common.names.custom" (list . "docs") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.csghub.portal.docs.host }}
    ports:
      - port: {{ .Values.csghub.portal.docs.port }}
{{- end }}
---
