{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.gitaly.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: |
      {{ include "common.names.custom" (list . "user") }}
    resource.dependencies/statefulsets: |
      {{ include "common.names.custom" . }}
data:
  config.toml: |
    ## Gitaly configuration (default)
    # The directory where Gitaly's executables are stored
    bin_dir = "/usr/local/bin"

    # listen on a TCP socket. This is insecure (no authentication)
    listen_addr = "0.0.0.0:8075"

    # Git executable settings
    [git]
    use_bundled_binaries = true

    # storage configuration, expected in $HOME
    [[storage]]
    name = "default"
    path = "/var/opt/gitaly/repositories"

    [logging]
    format = "json"
    level = {{ .Values.logging.level | quote }}
    dir = "/var/log/gitaly"

    [auth]
    token = {{ include "gitaly.internal.token" . | quote }}

    [gitlab]
    # # URL of the GitLab server.
    url = {{ printf "http://%s:%s" (include "common.names.custom" (list . "server")) (include "csghub.svc.port" "server") | quote }}
    # # 'relative_url_root' is only needed if a UNIX socket is used in 'url' and GitLab is configured to
    # # use a relative path. For example, '/gitlab'.
    # relative_url_root = '/'
    # # Path of the file containing the secret token used to authenticate with GitLab. Use either 'secret_token' or 'secret'
    # # but not both.
    # secret_file = "/opt/gitaly/.gitlab_shell_secret"
    # # Secret token used to authenticate with GitLab.
    secret = "signing-key"
    {{- end }}