{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.enabled .Values.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4  }}
    {{- end  }}
spec:
  ingressClassName: nginx
  {{- if eq (include "global.ingress.tls.enabled" .) "true" }}
  tls:
    - hosts:
        - {{ include "casdoor.external.domain" . }}
      {{- $secret := coalesce (include "global.ingress.tls.secret" .) .Values.ingress.tls.secretName }}
      {{- if $secret }}
      secretName: {{ $secret }}
      {{- else }}
      {{ fail "Minio ingress TLS is enabled but no secretName is provided." }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ include "casdoor.external.domain" . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "common.names.custom" . }}
                port:
                  number: {{ .Values.service.port }}
              {{- else }}
              serviceName: {{ include "common.names.custom" . }}
              servicePort: {{ .Values.service.port }}
              {{- end }}
{{- end }}