{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.builder (omit .Values "global" "exports") }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  serviceName: {{ include "common.names.custom" . }}
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with $conf.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- with (or $conf.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with $conf.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if $conf.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" . }}
      automountServiceAccountToken: {{ $conf.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-redis
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/redis:7.2.5
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          command: [ "redis-cli", "-h", "$(REDIS_HOST)", "-p", "$(REDIS_PORT)", "-a", "$(REDIS_PASSWD)", "ping" ]
          envFrom:
            {{- if .Values.global.redis.enabled }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            {{- else }}
            - configMapRef:
                name: {{ include "common.names.custom" . }}
            {{- end }}
      containers:
        - name: builder
          image: {{ $conf.image.repository }}:{{ $conf.image.tag }}
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: builder
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" . }}
            {{- if .Values.global.redis.enabled }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            {{- end }}
            {{- if .Values.global.registry.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "registry") }}
            {{- end }}
          env:
            - name: DOCKER_HOST
              value: "tcp://{{ include "common.names.custom" . }}:2375"
            {{- with $conf.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- $conf.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- $conf.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/data
              readOnly: false
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
            {{- if .Values.global.ingress.tls.enabled }}
            - name: certs
              mountPath: /usr/local/share/ca-certificates
            {{- end }}
        - name: docker
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/docker:27.1.2-dind
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          ports:
            - containerPort: 2375
              name: docker
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" . }}
            {{- if .Values.global.redis.enabled }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            {{- end }}
            {{- if .Values.global.registry.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "registry") }}
            {{- end }}
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: DOCKER_DRIVER
              value: overlay2
            - name: DOCKER_TLS_CERTDIR
              value: ""
          resources:
            {{- $conf.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 2375
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- $conf.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: docker-daemon
              mountPath: /etc/docker
              readOnly: true
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: docker-daemon
          configMap:
            name: {{ include "common.names.custom" (list . "builder-docker-daemon") }}
        - name: docker-config
          secret:
            secretName: {{ include "common.names.custom" (list . "registry-docker-config") }}
            items:
              - key: .dockerconfigjson
                path: config.json
        {{- if .Values.global.ingress.tls.enabled }}
        - name: certs
          secret:
            {{- if .Values.global.ingress.tls.autoGenerated }}
            secretName: {{ include "common.names.custom" (list . "certs") }}
            {{- else }}
            secretName: {{ .Values.global.ingress.tls.secretName }}
            {{- end }}
        {{- end }}
      {{- with $conf.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $conf.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $conf.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "common.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
          {{- with $conf.annotations }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes: {{ $conf.persistence.accessMode }}
        {{- if $conf.persistence.storageClass }}
        storageClassName: {{ $conf.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ $conf.persistence.size }}