{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.minio (omit .Values "global" "exports") }}
{{- $ingress := merge .Values.global.ingress .Values.ingress }}
{{- if and $conf.enabled $ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers read_ip_header X-Real-IP;
      chunked_transfer_encoding off;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-NginX-Proxy true;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    {{- if $conf.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    {{- end }}
    {{- with $conf.ingress.annotations }}
    {{- toYaml . | nindent 4  }}
    {{- end  }}
spec:
  ingressClassName: nginx
  {{- if $ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "minio.external.domain" . }}
      {{- if $ingress.tls.autoGenerated }}
      secretName: {{ include "common.names.custom" (list . "certs") }}
      {{- else }}
      {{- if $ingress.tls.secretName }}
      secretName: {{ $ingress.tls.secretName }}
      {{- else }}
      {{ fail "Ingress TLS is enabled but no secretName is provided for the TLS certificate." }}
      {{- end }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ include "minio.external.domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "common.names.custom" . }}
                port:
                  number: {{ add $conf.service.port 1 }}
              {{- else }}
              serviceName: {{ include "common.names.custom" . }}
              servicePort: {{ add $conf.service.port 1 }}
              {{- end }}
          - path: /csghub-git
            pathType: Prefix
            backend:
              {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "common.names.custom" . }}
                port:
                  number: {{ $conf.service.port }}
              {{- else }}
              serviceName: {{ include "common.names.custom" . }}
              servicePort: {{ $conf.service.port }}
              {{- end }}
{{- end }}