{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.minio (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data }}
  {{- $username := "minio" | b64enc }}
  {{- $password := randAlphaNum 15 | b64enc }}
  {{- if $secretData }}
  {{- $username = index $secretData "MINIO_ROOT_USER" }}
  {{- $password = index $secretData "MINIO_ROOT_PASSWORD" }}
  {{- end }}
  {{- if $username }}
  MINIO_ROOT_USER: {{ $username }}
  {{- else }}
  {{ fail "A valid admin username entry is required!" }}
  {{- end }}
  {{- if $password }}
  MINIO_ROOT_PASSWORD: {{ $password }}
  {{- else }}
  {{ fail "A valid admin password entry is required!" }}
  {{- end }}
{{- end }}
