{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.postgresql (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data }}
  {{- $userList := $conf.databases }}
  {{- range $username := (append $userList "postgres") }}
  {{- $database := $username -}}
  {{- $password := include "postgresql.initPass" $database | b64enc }}
  {{- if $secretData }}
  {{- $password = index $secretData $username }}
  {{- end }}
  {{- if and $username $password }}
  {{ $username }}: {{ $password }}
  {{- end }}
  {{- end }}
{{- end }}
