{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.pdb.create }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if .Values.global.pdb.minAvailable }}
  minAvailable: {{ .Values.global.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.global.pdb.maxUnavailable ( not .Values.global.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.global.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}