{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.portal (omit .Values "global" "exports") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
data:
  CSGHUB_PORTAL_ON_PREMISE: "false"
  CSGHUB_PORTAL_SENSITIVE_CHECK: "false"
  CSGHUB_PORTAL_STARHUB_BASE_URL: {{ include "csghub.external.endpoint" . }}
  CSGHUB_PORTAL_STARHUB_API_KEY: {{ include "server.api.token" . }}
  {{- if .Values.global.ingress.tls.enabled }}
  CSGHUB_PORTAL_ENABLE_HTTPS: "true"
  {{- else }}
  CSGHUB_PORTAL_ENABLE_HTTPS: "false"
  {{- end }}
  {{- if .Values.global.postgresql.enabled }}
  CSGHUB_PORTAL_DATABASE_HOST: {{ include "postgresql.internal.domain" . }}
  CSGHUB_PORTAL_DATABASE_PORT: {{ include "postgresql.internal.port" . | quote }}
  CSGHUB_PORTAL_DATABASE_USERNAME: "csghub_portal"
  CSGHUB_PORTAL_DATABASE_NAME: "csghub_portal"
  {{- else }}
  {{- with $conf.postgresql }}
  CSGHUB_PORTAL_DATABASE_HOST: {{ default "127.0.0.1" .host }}
  CSGHUB_PORTAL_DATABASE_PORT: {{ default "5432" .port | quote }}
  CSGHUB_PORTAL_DATABASE_USERNAME: {{ default "postgres" .user }}
  CSGHUB_PORTAL_DATABASE_PASSWORD: {{ .password }}
  CSGHUB_PORTAL_DATABASE_NAME: {{ default "postgres" .database }}
  {{- end }}
  {{- end }}
  {{- if .Values.global.minio.enabled }}
  CSGHUB_PORTAL_S3_ENDPOINT: "{{ include "minio.external.endpoint" . | trimPrefix "http://" | trimPrefix  "https://" }}"
  CSGHUB_PORTAL_S3_BUCKET: "csghub-portal"
  CSGHUB_PORTAL_S3_REGION: "cn-north-1"
  {{- if .Values.global.ingress.tls.enabled }}
  CSGHUB_PORTAL_S3_ENABLE_SSL: "true"
  {{- else }}
  CSGHUB_PORTAL_S3_ENABLE_SSL: "false"
  {{- end }}
  {{- else }}
  {{- with $conf.objectStore }}
  CSGHUB_PORTAL_S3_ENDPOINT: {{ .endpoint }}
  CSGHUB_PORTAL_S3_ACCESS_KEY_ID: {{ .accessKey }}
  CSGHUB_PORTAL_S3_ACCESS_KEY_SECRET: {{ .accessSecret }}
  CSGHUB_PORTAL_S3_BUCKET: {{ .bucketName }}
  CSGHUB_PORTAL_S3_REGION: {{ .region }}
  CSGHUB_PORTAL_S3_ENABLE_SSL: {{ .ssl }}
  {{- end }}
  {{- end }}