{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.custom" (list . "user") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "user") | nindent 4 }}
  annotations: {{ .Values.csghub.user.annotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "user") | nindent 6 }}
  replicas: {{ .Values.csghub.user.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-server.yaml") . | sha256sum }}
        {{- with .Values.csghub.user.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" (dict "context" . "service" "user") | nindent 8 }}
    spec:
      {{- with (or .Values.global.image.pullSecrets .Values.csghub.server.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.csghub.user.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.csghub.user.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" (list . "user") }}
      automountServiceAccountToken: {{ .Values.csghub.user.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-server
          image: {{ or .Values.global.image.registry .Values.csghub.server.image.registry }}/busybox:latest
          imagePullPolicy: {{ .Values.csghub.server.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until nc -z {{ include "common.names.custom" (list . "server") }} {{ include "csghub.svc.port" "server" }}; do echo 'Wait for csghub-server to be ready'; sleep 2; done" ]
      containers:
        - name: user
          image: {{ or .Values.global.image.registry .Values.csghub.server.image.registry }}/{{ or .Values.global.image.name .Values.csghub.server.image.repository }}:{{ include "csghub.image.tag" (dict "tag" (or .Values.global.image.tag .Values.csghub.server.image.tag) "context" .) }}
          imagePullPolicy: {{ or .Values.global.image.pullPolicy .Values.csghub.server.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "update-ca-certificates && /starhub-bin/starhub user launch" ]
          ports:
            - containerPort: 8080
              name: user
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include  "common.names.custom" (list . "casdoor") }}
            - configMapRef:
                name: {{ include  "common.names.custom" (list . "server") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "nats") }}
          env:
            - name: OPENCSG_USER_SERVER_PORT
              value: "8080"
            - name: OPENCSG_USER_SERVER_SIGNIN_SUCCESS_REDIRECT_URL
              value: {{ printf "%s/server/callback" (include "csghub.external.endpoint" .) }}
            - name: OPENCSG_ACCOUNTING_NATS_URL
              value: "nats://$(NATS_USERNAME):$(NATS_PASSWORD)@{{ include "nats.internal.domain" . }}:{{ include "nats.internal.ports.api" . }}"
            {{- with .Values.csghub.user.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- .Values.csghub.user.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            {{- .Values.csghub.user.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: jwt-token-crt
              mountPath: /starhub-bin/casdoor
      volumes:
        - name: jwt-token-crt
          secret:
            secretName: {{ include "common.names.custom" (list . "casdoor") }}
      {{- with .Values.csghub.user.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.user.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.user.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}