{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.server (omit .Values "global" "exports") }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  replicas: {{ $conf.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with $conf.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- with (or $conf.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with $conf.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if $conf.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" . }}
      automountServiceAccountToken: {{ $conf.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-postgresql
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/postgres:15.7
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until pg_isready -h $(STARHUB_DATABASE_HOST) -p $(STARHUB_DATABASE_PORT) -d $(STARHUB_DATABASE_NAME) -U $(STARHUB_DATABASE_USERNAME); do echo 'Waiting for PostgreSQL can be connected'; sleep 3; done" ]
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" . }}
            {{- if .Values.global.postgresql.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "postgresql") }}
            {{- end }}
          env:
            - name: PGPASSWORD
              {{- if .Values.global.postgresql.enabled }}
              value: "$(csghub_server)"
              {{- else }}
              value: "$(STARHUB_DATABASE_PASSWORD)"
              {{- end }}
        {{- if .Values.global.gitaly.enabled }}
        - name: wait-for-gitaly
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/busybox:latest
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until nc -z {{ include "gitaly.internal.domain" . }} {{ include "gitaly.internal.port" . }}; do echo 'Waiting for gitea can be connected'; sleep 2; done" ]
        {{- else }}
        - name: wait-for-gitea
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/curlimages/curl:latest
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until curl -s {{ include "gitea.internal.endpoint" . }}/api/healthz; do echo 'Waiting for gitea can be connected'; sleep 2; done" ]
        {{- end }}
      containers:
        - name: server
          image: {{ $conf.image.repository }}:{{ $conf.image.tag }}
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          command: [ "/bin/bash", "-c" ]
          args: [ "update-ca-certificates && /starhub-bin/scripts/init.sh" ]
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" . }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "nats") }}
            {{- if .Values.global.gitea.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "gitea") }}
            {{- end }}
            {{- if .Values.global.postgresql.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "postgresql") }}
            {{- end }}
            {{- if .Values.global.minio.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "minio") }}
            {{- end }}
          env:
            - name: GITEA_USERNAME
              value: "$(GITEA_ADMIN_USER)"
            - name: GITEA_PASSWORD
              value: "$(GITEA_ADMIN_PASSWORD)"
            - name: STARHUB_SERVER_GITSERVER_USERNAME
              value: "$(GITEA_ADMIN_USER)"
            - name: STARHUB_SERVER_GITSERVER_PASSWORD
              value: "$(GITEA_ADMIN_PASSWORD)"
            - name: STARHUB_SERVER_MIRRORSERVER_USERNAME
              value: "$(GITEA_ADMIN_USER)"
            - name: STARHUB_SERVER_MIRRORSERVER_PASSWORD
              value: "$(GITEA_ADMIN_PASSWORD)"
            - name: STARHUB_SERVER_MIRRORSERVER_HOST
              value: "$(STARHUB_SERVER_GITSERVER_URL)"
            - name: OPENCSG_ACCOUNTING_NATS_URL
              value: "nats://$(NATS_USERNAME):$(NATS_PASSWORD)@{{ include "nats.internal.domain" . }}:{{ include "nats.internal.ports.api" . }}"
            - name: POSTGRES_PASSWORD
              {{- if .Values.global.postgresql.enabled }}
              value: "$(csghub_server)"
              {{- else }}
              value: "$(STARHUB_DATABASE_PASSWORD)"
              {{- end }}
            - name: STARHUB_DATABASE_DSN
              value: "postgresql://$(STARHUB_DATABASE_USERNAME):$(POSTGRES_PASSWORD)@$(STARHUB_DATABASE_HOST):$(STARHUB_DATABASE_PORT)/$(STARHUB_DATABASE_NAME)?sslmode=disable"
            {{- if .Values.global.minio.enabled }}
            - name: STARHUB_SERVER_S3_ACCESS_KEY_ID
              value: "$(MINIO_ROOT_USER)"
            - name: STARHUB_SERVER_S3_ACCESS_KEY_SECRET
              value: "$(MINIO_ROOT_PASSWORD)"
            {{- end }}
            {{- with $conf.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- $conf.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            {{- $conf.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: jwt-token-crt
              mountPath: /starhub-bin/casdoor
            {{- if .Values.global.ingress.tls.enabled }}
            - name: certs
              mountPath: /usr/local/share/ca-certificates
            {{- end }}
      volumes:
        - name: jwt-token-crt
          secret:
            secretName: {{ include "common.names.custom" (list . "casdoor") }}
        {{- if .Values.global.ingress.tls.enabled }}
        - name: certs
          secret:
            {{- if .Values.global.ingress.tls.autoGenerated }}
            secretName: {{ include "common.names.custom" (list . "certs") }}
            {{- else }}
            secretName: {{ .Values.global.ingress.tls.secretName }}
            {{- end }}
        {{- end }}
      {{- with $conf.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $conf.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $conf.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}